### ISSUE TITLE
Firefox Extension.

### ISSUE THREAD

**Issue by stacode123** [Abdallah-Alwarawreh/Syrup#1]
Is it possible that a firefox version could be made?

**Comment by Abdallah-Alwarawreh** [comment]
Hmm, I will look into that and make a new build, thanks for notifying me on this

**Comment by Abdallah-Alwarawreh** [comment]
@stacode123  I pushed an update to the extension, now it should work for firefox

**Comment by pizzav-xyz** [comment]
is there a release made for the firefox version?

**Comment by pizzav-xyz** [comment]
also the readme says firefox supports chrome extensions or it looks like it does
